import type { Metadata } from "next";
import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
* component.
* This is the root layout for the application.
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /*
  *
  */
  const _config = {};
  
  //
  const _helpers = {
    getAppHeader: () => {
      return (
        <header style={{ background: '#111', color: '#fff', padding: '1rem' }}>
          <h1>My App</h1>
        </header>
      );
    },
    getAppMenu: () => {
      return(
        <aside
            style={{
              width: '200px',
              background: '#f4f4f4',
              padding: '1rem',
              borderRight: '1px solid #ccc',
            }}
          >
            <nav>
              <ul style={{ listStyle: 'none', padding: 0 }}>
                <li><Link href="/">Dashboard</Link></li>
                <li><Link href="/poker">Poker</Link></li>
                {/* Add more modules here */}
              </ul>
            </nav>
          </aside>
      );
    },
    getAppFooter: () => {
      return(
        <footer
          style={{
            background: '#eee',
            padding: '1rem',
            borderTop: '1px solid #ccc',
            textAlign: 'center',
          }}
        >
          &copy; 2025 My App
        </footer>
      );
    }
  };

  //
  const _actions = {};

  /*
  * component return.
  */
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* App-Header */}
        {_helpers.getAppHeader()}

        {/* Main Content */}
        <div style={{ display: 'flex', minHeight: '100vh' }}>
          {/* App-Menu */}
          {_helpers.getAppMenu()}
          {/* Main Content */}
          <main style={{ flex: 1, padding: '1rem' }}>{children}</main>
        </div>
        {/* Footer */}
        {_helpers.getAppFooter()}
      </body>
    </html>
  );
}
